### ISSUE TITLE
Add support for experimental map

### ISSUE THREAD

**Issue by KevinPeelman** [LancelotP/satisfactory-map#34]
**Is your feature request related to a problem? Please describe.**
The experimental build has different resource nodes etc. For reference read the patch notes for v0.1.5 Build 98224, section 'World'.  It would be really nice and helpful to see which nodes have been updated, moved, etc.

**Describe the solution you'd like**
A radio button in the settings panel to select normal or experimental build.

**Describe alternatives you've considered**
The experimental build has in ingame map, but resource nodes onthat map are only visible temporarily and only while scanning for them (so also in a limited range). I know that this map is kinda overpowered in comparison to the ingame one, but it makes gameplay way more fun.

**Comment by S4XXX** [comment]
Hello @Kevinator89 !

This is planned and 'already' fixed but not yet released on servers. Owner (@LancelotP ) is currently on vacation and I can't push changes to live servers.

Fixs are related to :
1) node locations were changed, deleted or added
2) the 'locate me' feature is patched for the experimental build (see https://github.com/LancelotP/satisfactory-map/issues/33 for further infos)

One issue still occurs : how should we take into account this experimental build ? Your suggestion is a good idea but I need to investigate a bit more with @LancelotP . My big deal is about the purpose of this integration. The game is still in early access (changes occurs frequently), and we should take into account a second build which is the early access of an early access ...

I think a lot of people are wrong: the experimental version is not made to play in the long term (ie to advance in its save) but only to test future features and give its opinion

Nevertheless, I presume we'll choose a solution like your suggestion, but as we work on this project on our free time, i also want to be sure to stay alive to keep this up to date :D

Thank you for your interest about our tool :)

**Comment by bbakermmc** [comment]
@S4XXX I disagree with the experimental server inst for long term place, its no diff than like MMOs where guilds only play on the Beta/PTR servers.  Its just the bleeding edge version.  And if you want to get technical the early access is beta too so why even have a map until its released 📦 
Whats the ETA on his return, or is there a branch of code we run ourselves?

**Comment by S4XXX** [comment]
@bbakermmc The difference also stems from the fact that the stable version is (like its name suggests) more stable and updated much less often than the experimental version that has been updated 6 times in 10 days (mostly fixes or even rollbacks ...). It will be difficult for us to track everything if the nodes change places every 2 days for example. However we are setting up a solution to generate static data (items locations, type, purity, obstructed, etc) by sending a save in our script, for my part I almost finished, @LancelotP must do the integration, surely during the weekend

**Comment by Kevinator89** [comment]
I totally agree that keeping up to date with the experimental build might be very time consuming as they update this branch pretty often. However, if you read a bit deeper into their explanation for a handcrafted map, they state that they want a nice, balanced (and bug free) map for everyone instead of a constantly updated, changed or procedurally generating one. They also strive for backwards compatibility and thus want to keep map changes to a bare minimum.
I have read some other issues on this repo and had the following proposal to solve some of them:
If you want to load players' saves and show them more than just their location (eg also which slugs, spheres, pods etc they picked up), why cant you load all data (also node locations, game version,...) from the save, so that when a new version is released, you dont need to update the map because it will automatically read all the new locations from players' uploaded saves.
I know that this might be quite a big change to implement right now but it might save you loads of time in the future.

**Comment by S4XXX** [comment]
We thought about this, but there is actually no clue to know which build a save came from :/ Then we can't trust user's data to fill node locations, in fact we could, if someone delete some nodes or play around with it, it's not our deal. Another issue is that type and purity of nodes are not stored in the save file, we filled data manually. When I regenerate a dataset for a new build, i try my best to match nodes thanks to IDs I built. But we need to fill the new ones :/

So basically what we achieve right now is an improvement of our static data generation script. We've got 2 build types (stable, experimental). Users can change build types on the map. Each types got a list of versions. Each version got a set of static data. We can generate a dataset for a new version with a new save and by linking  data filled by hand from previous version of the same build type.
The map shows the most recent version of the chosen build type.

I hope it's pretty well summarized x)

**Comment by bbakermmc** [comment]
@S4XXX can you provide some of outputs of the save files and your data files for referencing?

I think youre on the right path with you version data per build #, and if you get a new node or a location changed then maybe prompt the user for the build number?

Some of this could be community driven, if there isnt a way to pull it from the save file/exe/api at some point.

Sometime it might be easier to just look at the datasets to find things, IE when you want to go on HD hunts, maybe I dont want to deal with power.

Right now I would just like to know on the EXP what the new oil values are :) since current map shows normal, but its actually impure

You guys doing good work, I think the data modeling just needs a few tweaks and you could support any version, (As long as map doesnt drastically change).

**Comment by petestrash** [comment]
1. The locate me feature is still not working, even for new saves from early access (if it was used in the experimental).  Do we have an ETA for the Server update?

2. How can we as users help tag the purity of nodes for you as you can't get this from the save files?

Pete.

**Comment by LancelotP** [comment]
Hello Pete,

1. @S4XXX is working on it as we speak, I'll let him follow up on the thread
2. At the moment we do not have a reporting system (I'm working on it right now) but for the time being you can just [post it here](https://github.com/LancelotP/satisfactory-map/issues/37) that will help us keep things contained in one place

**Comment by petestrash** [comment]
Any further update on this?

**Comment by LancelotP** [comment]
@petestrash No news from s4xxx at the moment, I'll try to look at it ASAP. Need to update the nodes first ;)

**Comment by petestrash** [comment]
Just letting you know the locate me feature is now working for me again.
