### ISSUE TITLE
Missing or Incomplete Data

### ISSUE THREAD

**Issue by LancelotP** [LancelotP/satisfactory-map#37]
Since we do not have any reporting system yet this thread is here for everyone to report any missing or incomplete node information about the map.

**Comment by FTLNewsFeed** [comment]
Since a lot of the Swamp and NE Desert was changed I ran through there to see what was new and came up with this list. It's not exhaustive, but it's a start. All of the new nodes in the south part of the NE Desert are ping-able and I have put miners on and chipped iron from them even though there's no artwork showing the node there. The Upgrade/Downgrade/Changed nodes in the Swamp are the coordinates pulled from your map, the rest are me trying to stand by or on the node and reading the coordinates the command line 'showdebug radiationspheres' gave me. 

Swamp:
====================
New Limestone Normal X = 186169.36 Y = 77003.77 Z = 3131.96
Upgrade Limestone Normal to Limestone Pure X = 284986.28125 Y = 111894.0703125 Z = -1605.71484375
Upgrade Iron Normal to Iron Pure X = 271770.6875 Y = 100432.4765625 Z = -1294.7979736328125
Upgrade Caterium Normal to Caterium Pure X = 270786.0625 Y = 120111.015625 Z = -54.522705078125
New Copper Pure X = 225482.41 Y = 55799.05 Z = -1205.00
New Limestone Pure X = 21997083 Y = 42309.41 Z = -1534.09
Downgrade Iron Pure to Iron Normal X = 245700.4375 Y = 30065.3984375 Z = -847.2978515625
Changed Coal Pure to Iron Normal X = 252751.21875 Y = 29139.623046875 Z = -798.658935546875
Downgrade Limestone Pure to Limestone Normal X = 270772.25 Y = 47035.5703125 Z = -1613.823852539062
Downgrade Copper Pure to Copper Normal X = 282284.1875 Y = 63326.75390625 Z = -1601.3115234375

Upgrade Sulfur Normal to Sulfur Pure X = 296499.78125 Y = 13253.51171875 Z = -881.7694091796875
New Copper Normal X = 297535.88 Y = -7436.12 Z = -204.52

NE Desert:
======================
New Iron Pure X = 262443.53 Y = -118937.57 Z = 5824
New Iron Pure X = 308663.47 Y = 149748.97 Z = 4319.93
New Iron Pure X = 311576.34 Y = -131121.55 Z = 5419.82
New Iron Pure X = 301116.63 Y = -112396.91 Z = 5501.05
New Iron Pure X = 336426.22 Y = -119485.55 Z = 7241.88
New Iron Pure X = 346551.00 Y = -150597.05 Z = -4360.02

**Comment by Captnwalker1** [comment]
Oil nodes that are now on northern shore have some incorrect puritys:
PL_RN_31_104 is IMPURE
PL_RN_32_105 is IMPURE
PL_RN_27_100 is PURE
PL_RN_26_99 is PURE
PL_RN_25_98 is IMPURE
PL_RN_23_96 is IMPURE
PL_RN_24_97 is IMPURE

**Comment by FTLNewsFeed** [comment]
In addition to Captnwalker1, the following Oil nodes have had their purity changed:

Dune Canyons, NE of Northern Forest:
X: 176296.8125 Y: -94196.8359375 Z: 1419.1478271484375 PL_RN_447 Downgrade from Normal to Impure
X: 167391.5 Y: -88953.6015625 Z: 1049.76953125 PL_RN_446_1 Downgrade from Normal to Impure

Dune Canyons, NW of Northern Forest:
X: -34085.078125 Y: -193714.984375 Z: 2280.0439453125 PL_RN_15 Downgrade from Normal to Impure
X: -44360.140625 Y: -189109.359375 Z: 2291.037841796875 PL_RN_16 Downgrade from Normal to Impure

**Comment by LancelotP** [comment]
Just rolled out an update, thanks a lot @FTLNewsFeed and @Captnwalker1 please feel free to tell me if I missed something

**Comment by Captnwalker1** [comment]
Unmarked Limestone node. Coordinates using console's `ShowDebug Camera`, seems off? Screenshot attached for reference
X: 120712 Y: -88448 Z: 13950 purity Normal
![limestone-node](https://user-images.githubusercontent.com/369858/57986944-2dbbe280-7a49-11e9-848a-3234ef53477a.jpg)

**Comment by FTLNewsFeed** [comment]
@Captnwalker1 I believe that's PL_RN_465 on the map.

**Comment by FTLNewsFeed** [comment]
DropPod PE_DP_6 Needs 2 Supercomputers
DropPod PE_DP_1_1 Needs 42 MWH & 8 Crystal Oscillator
DropPod PE_DP_9 Needs 1 Quantum Computer
DropPod PE_DP_3_3 Needs 5 Superposition Oscillator
DropPod PE_DP_2_2 Needs 67 MWH & 2 Turbo Motor
DropPod PE_DP_8 Needs 73 MWH & 3 A.I. Limiter

**Comment by Captnwalker1** [comment]
> @Captnwalker1 I believe that's PL_RN_465 on the map.

I thought so too but thats actually West-Southwest of the sulfur node, heres a screenshot with the existing limestone nodes and the new one, as well as the sulfur.

![limestone-node2](https://user-images.githubusercontent.com/369858/57988155-aa09f200-7a58-11e9-8dce-85144a744f1b.jpg)

**Comment by FTLNewsFeed** [comment]
A couple more:

X: 245861.546875 Y: 4378.94287109375 Z: 573.6340942382812 ID: PL_RN_567 is now Pure
New Iron Pure X = 255561.14 Y = -2856.30 Z = 3728.98 (I believe that this replaced the Impure SAM node (PL_RN_78_1097) that now has its own artwork and is much farther down in the Swamp)
New Iron Pure X = 242859.44 Y = 87966.32 Z = -465.30

**Comment by LancelotP** [comment]
@FTLNewsFeed about PL_RN_78_1097 we still have it referenced in the files as follow :

```javascript
{
  x: 226981.953125,
  y: 105989.8828125,
  z: -1348.8350830078125,
  originId: "PL_RN_78_1097",
}
```

Are you sure it has been replaced?

On another note we have two nodes missing at the moment:

```javascript
{
    x: 270422.25,
    y: -136077.84375,
    z: 4392.4169921875,
    originId: "PL_RN_436",
    obstructed: false,
    type: 'unknown',
    purity: 'unknown'
  },
{
    x: 225430.5,
    y: -6949.228515625,
    z: -1549.86083984375,
    originId: "PL_RN_69",
    obstructed: false,
    type: 'unknown',
    purity: 'unknown'
  },
```

Good job for finding the other ones you helped us a lot :)

**Comment by S4XXX** [comment]
notes to myself:

![swamp_pods](https://user-images.githubusercontent.com/9801541/57997008-d1010c00-7aca-11e9-973c-f1e876c030b5.jpg)

- DropPod PE_DP_2_1 - 20mwh + 27 Encased Industrial Beams
- DropPod PE2_DP_5_6 - 10 Rubber

**Comment by LancelotP** [comment]
@S4XXX Do you want me to deploy your notes ?

**Comment by FTLNewsFeed** [comment]
@LancelotP Yup, the node's been replaced. PL_RN_78_1097 used to be an Impure SAM node at A (see picture). It got moved down to B -- I previously had a miner at A for when SAM was activated, and when SAM node B showed up it wouldn't let me place a miner there, so I went searching around for the miner and once I found it and removed it from A I was allowed to place a miner on B. The node is still there at A, but it's a Pure Iron node now. (Just ran up to A and double checked and yup, it's a Pure Iron node now : ) )
![AtoB](https://user-images.githubusercontent.com/50793738/57998481-88276400-7a86-11e9-813d-0f2ec40879a1.jpg)

I went searching for PL_RN_436 and around where the coordinates are all that I found was that the Z coordinate was up in the air. Given that they have a Uranium node up in the air at the moment it wouldn't surprise me if something is there, but nothing that's currently ping-able showed up.

PL_RN_69 is a Pure Limestone node.

**Comment by S4XXX** [comment]
@LancelotP If you have time, enjoy yourself

**Comment by LancelotP** [comment]
@S4XXX done
@FTLNewsFeed done for the limestone, ok for the uranium, need some more research on that missing iron node I'll try checking tonight we don't have any references to it that's odd I hope they didn't change the file format for the nodes on this one...

**Comment by FTLNewsFeed** [comment]
There's a Pure Iron node at X = 270239.94 Y = -136404.97 Z = 4399.71

**Comment by EJaxx** [comment]
PL_RN_436 @(270422.25, -136077.84375, 4392.4169921875) is Pure Iron
![Screenshot1](https://user-images.githubusercontent.com/51190289/58617740-632ebe80-82da-11e9-900c-c4897a30fd9a.jpg)

**Comment by LancelotP** [comment]
@FTLNewsFeed @EJaxx Fixed just now, thanks for the report. Deploy is in progress should be live in ~ 10 minutes

**Comment by dmigowski** [comment]
Hello, 

this is the nodes.ts for the current experimental branch containing of course all the bauxit in the new locations and EVERYTHING else. It was create programmatically by me from extracting stuff from the game. You won't find any errors in it, that is the way to go.

[nodes.ts.txt](https://github.com/LancelotP/satisfactory-map/files/3315397/nodes.ts.txt)

PS: It was created by placing miners programmatically on all nodes of a clean new game, including a small burner with a few leaves in it. Then I checked how much i could extract given the limited power. The resulting ores exactly states the node purity and types. Enjoy.

**Comment by petestrash** [comment]
Thanks a lot for that it's must have been a lot of work.

**Comment by LancelotP** [comment]
@dmigowski Wow that's ludicrous, would you care contributing to a script of something to replicate the process for further versions down the road?

I'll try to release it tonight.

Thanks again mate.

**Comment by dmigowski** [comment]
Will try this weekend... until then I can provide new data in a few minutes after a new version has been released... or after I take note of it ;)

**Comment by LancelotP** [comment]
@dmigowski both options works for me. Thanks again, I'm trying to find a way to be compliant with the calculator that embed the app, release will follow shortly ;)

**Comment by dmigowski** [comment]
Hi, are there still problems with my data? I used your format, so why not simply replacing the file?

**Comment by LancelotP** [comment]
No, the data is fine, I just need to have a toggle to switch between stable and experimental build. And also make it compatible with the integration greeny uses on his site ;).

**Comment by LancelotP** [comment]
Following @dmigowski suggestion I've made a script that extract purities and types of nodes. This thread is not needed anymore as the update just got live.

Thanks again.
